### ISSUE TITLE
Wrong check CMAKE_SHARED_LIBRARY_PREFIX on 64bit systems

### ISSUE THREAD

**Issue by sibskull** [tylert/trustedqsl-tqsl#1]
https://github.com/tylert/trustedqsl-tqsl/blob/f2ad7207e8d9ee4ea11f40b93058e3750c6dcddc/CMakeLists.txt#L10

According https://cmake.org/cmake/help/v3.0/variable/CMAKE_SHARED_LIBRARY_PREFIX.html 
The prefix to use for the name of a shared library, lib on UNIX. This value is always "lib" on Unix because this is part of library file name, not path.

There is solution in  https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html - use standard path CMAKE_INSTALL_LIBDIR for installed libraries.

**Comment by sibskull** [comment]
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 8f7eb36..ff482e7 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -1,5 +1,5 @@
 project (tqsllib)
-
+include(GNUInstallDirs)
 set(OSX_ARCH i386 CACHE STRING "Architectures to build for OSX")
 
 string(REPLACE " " ";" CMAKE_OSX_ARCHITECTURES ${OSX_ARCH})
@@ -56,7 +56,7 @@ include_directories(${OPENSSL_INCLUDE_DIR} ${ZLIB_INCLUDE_DIR} ${EXPAT_INCLUDE_D
 if(NOT APPLE AND NOT WIN32)
 set_source_files_properties(location.cpp PROPERTIES COMPILE_DEFINITIONS CONFDIR="${CMAKE_INSTALL_PREFIX}/share/TrustedQSL/")
 set(HEADERS_TO_INSTALL tqsllib.h tqslerrno.h cabrillo.h adif.h tqslconvert.h)
-install(TARGETS tqsllib DESTINATION lib${LIB_SUFFIX})
+install(TARGETS tqsllib DESTINATION ${CMAKE_INSTALL_LIBDIR})
 install(FILES config.xml DESTINATION share/TrustedQSL)
 install(FILES ${HEADERS_TO_INSTALL} DESTINATION include)
 endif()
```

**Comment by tylert** [comment]
Спасибо!  I would ask you to please submit your PR to the primary upstream project at https://sourceforge.net/p/trustedqsl/tqsl/ci/master/tree/.

My fork is merely a clone of that project with a slightly nicer interface (which I frequently forget to update).
